export const RECEIVE_TASKS = 'RECEIVE_TASKS';
export const UPDATE_FORM_VALUES = 'UPDATE_FORM_VALUES';
export const CLEAR_FORM_VALUES = 'CLEAR_FORM_VALUES';
export const SET_PAGE = 'SET_PAGE';
export const SET_SORT_TYPE = 'SET_SORT_TYPE';
export const SET_SORT_DIRECTION = 'SET_SORT_DIRECTION';
